### ISSUE TITLE
Readme example doesn't work

### ISSUE THREAD

**Issue by kennetpostigo** [xfrr/goffmpeg#65]
I'm new to ffmpeg but I get an error running the example in the readme. I created the input file, but it errors with:
```go
src/converter/main.go:16:2: err declared but not used
```

After using err in an control flow check I get this printed out in my terminal:
```sh
❯ go run src/converter/main.go
panic: error executing ([-i test.mov -print_format json -show_format -show_streams -show_error]) | error: exit status 1 | message: {
    "error": {
        "code": -2,
        "string": "No such file or directory"
    }
}
 ffprobe version 4.2.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.59)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags=-fno-stack-check --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
test.mov: No such file or directory


goroutine 1 [running]:
main.convert()
        /Users/kennetpostigo/Projects/specter/go/specter-api/src/converter/main.go:21 +0x335
main.main()
        /Users/kennetpostigo/Projects/specter/go/specter-api/src/converter/main.go:13 +0x20
exit status 2
```

From this:
```go
package main

import (
  "fmt"

  "github.com/xfrr/goffmpeg/transcoder"
)

var inputPath = "test.mov"
var outputPath = "test.mp4"

func main() {
  convert()
}

func convert() {
  trans := new(transcoder.Transcoder)

  err := trans.Initialize(inputPath, outputPath)
  if err != nil {
    panic(err)
  }

  done := trans.Run(true)

  progress := trans.Output()
  for msg := range progress {
    fmt.Println(msg)
  }

  if err = <-done; err != nil {
    panic(err)
  }
}

```

Do you know what I may be doing wrong here?

**Comment by kennetpostigo** [comment]
I figured out the issue, got it working. Sorry about the issue.
