### ISSUE TITLE
Trying to convert MP4 to HLS

### ISSUE THREAD

**Issue by kennetpostigo** [xfrr/goffmpeg#66]
Hi 👋,

So I was able to get `goffmpeg` to convert a `.mov` -> `mp4`. Based of the example from the readme. I did a bit of digging into old issues and current ones to try to piece together how to convert the `.mp4` I got into `HLS`. 

Here's what I got:
```sh
❯ go run src/converter/main.go
panic: Failed Finish FFMPEG ([-nostats -loglevel 0 -y -i data/test.mp4 -c:v copy -hls_list_size 10 -hls_time 10 -hls_key_info_file  data/test.m3u8]) with exit status 1 message  

goroutine 1 [running]:
main.convert()
        /src/converter/main.go:32 +0x1c8
main.main()
        /src/converter/main.go:11 +0x20
exit status 2
```

From my go code:
```go
package main

import (
  "github.com/xfrr/goffmpeg/transcoder"
)

var inputPath = "data/test.mp4"
var outputPath = "data/test.m3u8"

func main() {
  convert()
}

func convert() {
  trans := new(transcoder.Transcoder)

  err := trans.Initialize(inputPath, outputPath)
  if err != nil {
    panic(err)
  }

  // Copy video streams
  trans.MediaFile().SetVideoCodec("copy")
  // Set hls list size
  trans.MediaFile().SetHlsListSize(0)
  // Set HLS time
  trans.MediaFile().SetHlsSegmentDuration(10)

  done := trans.Run(false)

  if err = <-done; err != nil {
    panic(err)
  }
}
```

Any chance you know what I may be doing wrong here?

**Comment by kennetpostigo** [comment]
Sorry, stale bot, I'm still interested in knowing what I may be doing wrong here

**Comment by liuche692326532** [comment]
same problem with me, I deployed my project use docker in centOs8, installed ffmpeg 4.3.2. an it throw error: 
panic: Failed Finish FFMPEG...with exit status 1 message
